name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build iOS Framework
        run: ./gradlew :composeApp:assembleXCFramework

      - name: Upload XCFramework Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcframework
          path: composeApp/build/XCFrameworks
